version: "3"

services:

  ############################################## PostgreSQL Server #############################################

  postgres:
      image: postgres
      container_name: postgres
      hostname: postgres
      ports: 
        - 5433:5432
      environment: 
        POSTGRES_HOST_AUTH_METHOD: 'trust'

  ############################################### NODEJS Server ###############################################

  nodeServer:
    image: tasktrack.telekom.at/parma-poc-docker-local/graphql-poc01
    container_name: nodeServer-01
    hostname: nodeServer
    ports: 
      - 5000:5000
    environment: 
        POSTGRES_HOST: "postgres"
        POSTGRES_PORT: "5432"
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "postgres"
        POSTGRES_DATABASE: "graphql_poc01"
    depends_on: 
      - postgres