version: "3"

services:

  ############################################### NODEJS Server ###############################################

  postgres:
      image: postgres
      container_name: postgres
      hostname: postgres
      environment: 
          POSTGRES_PASSWORD: "postgres"
      volumes: 
        - ./_data:/var/lib/postgresql/data
      

  ############################################### NODEJS Server ###############################################

  nodeServer:
    image: 311200/graphql-poc01
    container_name: nodeServer
    hostname: nodeServer
    ports: 
      - 5000:5000
    environment: 
        POSTGRES_HOST: "postgres"
        POSTGRES_PORT: "5432"
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "postgres"
        POSTGRES_DATABASE: "graphql_poc01"
    depends_on: 
      - postgres